<!DOCTYPE html>
<link rel="icon" href="data:,">
<meta name="viewport" content="width=device-width,initial-scale=1.0">
<title>Article 1</title>
<?php

//valid html document





echo '<p>Language purists will have to get real cool with internet buzzwords and slangs those &quot;darn kids&quot; make up really quickly, because <a href="https://www.engadget.com/2017-02-07-merriam-webster-dictionary-adds-crispr-binge-watch-botnet.html">Merriam-Webster</a> has legitimized a bunch by <a href="https://www.merriam-webster.com/words-at-play/new-words-in-the-dictionary">adding them to its dictionary</a>. The addition of &quot;metaverse&quot; comes as no surprise, seeing as companies like Facebook have been all about the virtual environment recently in meatspace. Yes, &quot;meatspace&quot; is a term now used to describe physical space and environment. &quot;Altcoin&quot; has also been added to describe alternatives to established cryptocurrencies, such as Bitcoin.&nbsp;</p><p>People have been saying &quot;laggy&quot; and &quot;pwn&quot; for a very, very long time now, but now those words have their own pages on the dictionary&#39;s website. And those who want to tell someone on the internet that they&#39;re &quot;virtue signaling&quot; or &quot;greenwashing&quot; something can now simply link them to those terms.&nbsp;</p><span id="end-legacy-contents"></span><p>When the game <a href="https://www.engadget.com/among-us-vr-beta-test-signups-163952272.html"><em>Among Us</em></a> rose in popularity, so did the slang &quot;sus,&quot; which means suspicious or suspect, so it&#39;s not a mystery why Merriam-Webster has officially recognized it. The word &quot;lewk,&quot; as in fashion looks, is now officially a word, as well. We hope nobody &quot;cringes&quot; or &quot;yeets&quot; whatever it is they&#39;re holding, but &quot;adorkable&quot; has also been added to the dictionary. (Yep, &quot;cringe&quot; and &quot;yeet&quot; get their own dictionary entries, too.)</p><p>The list of new words includes additions that clearly illustrate how these past years have gone for everyone. &quot;Booster dose,&quot; which became a commonly uttered phrase because of the pandemic, gets its own Merriam-Webster page, so do &quot;false positive&quot; and &quot;false negative&quot; lab test results. The words &quot;shrinkflation,&quot; the practice of reducing a product&#39;s amount or volume while offering it at the same price, and &quot;side hustle&quot; are also part of the list and will serve as reminders for years to come about the state of the economy in 2022.&nbsp;</p><p>Merriam-Webster has <a href="https://www.merriam-webster.com/words-at-play/new-words-in-the-dictionary">posted</a> the full list of new words, which also include some delicious entries like &quot;pumpkin spice&quot; and &quot;birria,&quot; on its website.</p>';